# Generated by Django 2.0 on 2017-12-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_object_s2p_s3p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1', models.CharField(max_length=50, null=True)),
                ('T2', models.CharField(max_length=50, null=True)),
                ('T3', models.CharField(max_length=50, null=True)),
                ('T4', models.CharField(max_length=50, null=True)),
                ('T5', models.CharField(max_length=50, null=True)),
                ('T6', models.CharField(max_length=50, null=True)),
                ('T7', models.CharField(max_length=50, null=True)),
                ('T8', models.CharField(max_length=50, null=True)),
                ('T9', models.CharField(max_length=50, null=True)),
                ('T10', models.CharField(max_length=50, null=True)),
                ('T11', models.CharField(max_length=50, null=True)),
                ('T12', models.CharField(max_length=50, null=True)),
                ('T13', models.CharField(max_length=50, null=True)),
                ('T14', models.CharField(max_length=50, null=True)),
                ('T15', models.CharField(max_length=50, null=True)),
                ('T16', models.CharField(max_length=50, null=True)),
                ('T17', models.CharField(max_length=50, null=True)),
                ('T18', models.CharField(max_length=50, null=True)),
                ('T19', models.CharField(max_length=50, null=True)),
                ('T20', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
