# Generated by Django 2.0 on 2017-12-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='Positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='Possibility',
            field=models.IntegerField(default=100),
        ),
    ]
