# Generated by Django 2.0 on 2017-12-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171222_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='Count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='Positive',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='Possibility',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
