# Generated by Django 2.0 on 2018-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_objects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objects',
        ),
        migrations.AddField(
            model_name='object',
            name='name',
            field=models.CharField(default='thing', max_length=50),
        ),
        migrations.AddField(
            model_name='object',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
