# Generated by Django 2.0 on 2018-02-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20180202_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='temporary',
            field=models.NullBooleanField(),
        ),
    ]
