# Generated by Django 2.0 on 2018-02-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_object_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='temporary',
            field=models.NullBooleanField(default=False),
        ),
    ]
